### ISSUE TITLE
Unhandled Exception: FormatException: Invalid double

### ISSUE THREAD

**Issue by alialdwahy** [MohamedSayed9392/Game-Levels-Scrolling-Map#9]
I/flutter ( 4495): widget.height : 800.0
I/flutter ( 4495): pathSVG : 
E/flutter ( 4495): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Invalid double
E/flutter ( 4495): 
E/flutter ( 4495): #0      double.parse (dart:core-patch/double_patch.dart:112:28)
E/flutter ( 4495): #1      _GameLevelsScrollingMapState._getPathFromSVG.<anonymous closure> (package:game_levels_scrolling_map/game_levels_scrolling_map.dart:313:39)
E/flutter ( 4495): <asynchronous suspension>
E/flutter ( 4495): #2      _GameLevelsScrollingMapState._getPathFromSVG (package:game_levels_scrolling_map/game_levels_scrolling_map.dart:307:5)
E/flutter ( 4495): <asynchronous suspension>
E/flutter ( 4495): #3      _GameLevelsScrollingMapState.initState.<anonymous closure> (package:game_levels_scrolling_map/game_levels_scrolling_map.dart:91:9)
E/flutter ( 4495): <asynchronous suspension>
E/flutter ( 4495):

**Comment by abdelRahmanYoussry** [comment]
yes iam facing the same issue
